# Use a slim Python base image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the dependency file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the port the Flask app runs on (Port 5000 from run.py)
EXPOSE 5000

# Set an environment variable required by Flask to run the application
ENV FLASK_APP=run.py

# Command to run the application
CMD ["python3", "run.py"]